/*
 * SPDX-FileCopyrightText: 2023-2026 IacobIacob01
 * SPDX-License-Identifier: Apache-2.0
 */

package com.dot.gallery.cloud.core

import com.dot.gallery.cloud.core.capabilities.RemoteMediaProvider

/**
 * Parsed representation of a `cloud://` media URI, shared by every pipeline resolver
 * (Sketch fetcher, Glide model loader, ExoPlayer data source, ZoomImage source).
 *
 * Grammar: `cloud://{ProviderType}/{remoteId}[?size=thumbnail|preview|original][&type=person][&fileId=..][&cfg=..]`
 *
 * [remoteId] may itself contain slashes (e.g. WebDAV/ownCloud/SMB/NFS paths like
 * `Photos/IMG.jpg`), so the path is parsed manually rather than via `Uri.pathSegments`,
 * which would truncate it to the first segment and produce both a wrong request URL and a
 * colliding cache key. Previously this logic was duplicated in four resolvers.
 */
data class CloudUri(
    val providerType: ProviderType,
    val remoteId: String,
    val size: String,
    val typeParam: String?,
    val fileId: String?,
    val configId: Long
) {
    /**
     * Apply the grid-cell downgrade: when a small target is requested (a grid/album cell), serve
     * the cheap THUMBNAIL instead of the larger PREVIEW. Critical for network filesystems
     * (SMB/NFS) where PREVIEW is generated by downloading the entire original on-device.
     * `original`, person thumbnails, and non-positive ("origin") sizes are left untouched.
     */
    fun effectiveSize(requestedMaxPx: Int): String =
        if (typeParam == null && size != "original" && requestedMaxPx in 1..GRID_THUMBNAIL_MAX_PX) {
            "thumbnail"
        } else size

    companion object {
        const val SCHEME = "cloud"

        /** Targets at or below this longest-edge pixel size are treated as grid cells. */
        const val GRID_THUMBNAIL_MAX_PX = 600

        /** Parses a `cloud://` URI string, or returns null if it is not a valid cloud URI. */
        fun parse(uriString: String): CloudUri? {
            if (!uriString.startsWith("$SCHEME://")) return null
            val withoutScheme = uriString.removePrefix("$SCHEME://")
            val authorityEnd = withoutScheme.indexOf('/')
            if (authorityEnd == -1) return null

            val providerType = try {
                ProviderType.valueOf(withoutScheme.substring(0, authorityEnd))
            } catch (_: Exception) {
                return null
            }

            val pathAndQuery = withoutScheme.substring(authorityEnd + 1)
            val queryStart = pathAndQuery.indexOf('?')
            val remoteId = if (queryStart == -1) pathAndQuery else pathAndQuery.substring(0, queryStart)
            if (remoteId.isEmpty()) return null

            val params = if (queryStart != -1) {
                pathAndQuery.substring(queryStart + 1)
                    .split('&')
                    .mapNotNull { p ->
                        val idx = p.indexOf('=')
                        if (idx == -1) null else p.substring(0, idx) to p.substring(idx + 1)
                    }
                    .toMap()
            } else emptyMap()

            return CloudUri(
                providerType = providerType,
                remoteId = remoteId,
                size = params["size"] ?: "preview",
                typeParam = params["type"],
                fileId = params["fileId"],
                configId = params["cfg"]?.toLongOrNull() ?: -1L
            )
        }
    }
}

/**
 * Resolve the [RemoteMediaProvider] for a parsed cloud URI: prefer the exact account instance
 * ([CloudUri.configId]) and fall back to the first instance of the type for back-compat with
 * URIs minted before the `cfg` query param existed.
 */
fun ProviderRegistry.resolveRemote(providerType: ProviderType, configId: Long): RemoteMediaProvider? =
    ((if (configId > 0L) getByConfigId(configId) else null) ?: get(providerType)) as? RemoteMediaProvider
